//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur5RobotiqMover
{
    [Serializable]
    public class PlanToPoseResponse : Message
    {
        public const string k_RosMessageName = "ur5_robotiq_mover_msgs/PlanToPose";
        public override string RosMessageName => k_RosMessageName;

        public Trajectory.JointTrajectoryMsg trajectory;
        public bool success;

        public PlanToPoseResponse()
        {
            this.trajectory = new Trajectory.JointTrajectoryMsg();
            this.success = false;
        }

        public PlanToPoseResponse(Trajectory.JointTrajectoryMsg trajectory, bool success)
        {
            this.trajectory = trajectory;
            this.success = success;
        }

        public static PlanToPoseResponse Deserialize(MessageDeserializer deserializer) => new PlanToPoseResponse(deserializer);

        private PlanToPoseResponse(MessageDeserializer deserializer)
        {
            this.trajectory = Trajectory.JointTrajectoryMsg.Deserialize(deserializer);
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.trajectory);
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "PlanToPoseResponse: " +
            "\ntrajectory: " + trajectory.ToString() +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
