//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur5RobotiqMover
{
    [Serializable]
    public class PlanToPoseRequest : Message
    {
        public const string k_RosMessageName = "ur5_robotiq_mover_msgs/PlanToPose";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.JointStateMsg joints_input;
        public Geometry.PoseMsg target_pose;

        public PlanToPoseRequest()
        {
            this.joints_input = new Sensor.JointStateMsg();
            this.target_pose = new Geometry.PoseMsg();
        }

        public PlanToPoseRequest(Sensor.JointStateMsg joints_input, Geometry.PoseMsg target_pose)
        {
            this.joints_input = joints_input;
            this.target_pose = target_pose;
        }

        public static PlanToPoseRequest Deserialize(MessageDeserializer deserializer) => new PlanToPoseRequest(deserializer);

        private PlanToPoseRequest(MessageDeserializer deserializer)
        {
            this.joints_input = Sensor.JointStateMsg.Deserialize(deserializer);
            this.target_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joints_input);
            serializer.Write(this.target_pose);
        }

        public override string ToString()
        {
            return "PlanToPoseRequest: " +
            "\njoints_input: " + joints_input.ToString() +
            "\ntarget_pose: " + target_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
