//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MycobotMoverInterfaces
{
    [Serializable]
    public class PickPlaceResponse : Message
    {
        public const string k_RosMessageName = "mycobot_mover_interfaces/PickPlace";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        public string message;

        public PickPlaceResponse()
        {
            this.success = false;
            this.message = "";
        }

        public PickPlaceResponse(bool success, string message)
        {
            this.success = success;
            this.message = message;
        }

        public static PickPlaceResponse Deserialize(MessageDeserializer deserializer) => new PickPlaceResponse(deserializer);

        private PickPlaceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "PickPlaceResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
