//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MycobotMoverInterfaces
{
    [Serializable]
    public class PickPlaceRequest : Message
    {
        public const string k_RosMessageName = "mycobot_mover_interfaces/PickPlace";
        public override string RosMessageName => k_RosMessageName;

        public bool trigger;

        public PickPlaceRequest()
        {
            this.trigger = false;
        }

        public PickPlaceRequest(bool trigger)
        {
            this.trigger = trigger;
        }

        public static PickPlaceRequest Deserialize(MessageDeserializer deserializer) => new PickPlaceRequest(deserializer);

        private PickPlaceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.trigger);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.trigger);
        }

        public override string ToString()
        {
            return "PickPlaceRequest: " +
            "\ntrigger: " + trigger.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
